# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'SQliteExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLite.swift', :git => 'https://github.com/stephencelis/SQLite.swift.git', :branch => 'swift-4'	
  # Pods for SQliteExample

end
